// APIs consumidas pela interface profissional

export const usuarios = [
    {   id: 1,
        imagem: 'https://amafotos.s3.amazonaws.com/usuario7.png',
        nomeCompleto: 'Sandra Cardoso Alencar',
        nome: 'Sandra Alencar',
        cpf: '01112312301',
        dataNascimento: '1989-11-10',
        idade: '31',
        email: 'sandra.alencar@gmail.com',
        telefone: '81985529827',
        senha:'senha123',
        cep: '50910380',
        cidade: 'Recife',
        bairro: 'Santo Amaro',
        rua: 'Avenida Visconde de Suassuna',
        numero: '55',
        data: '24/10/2023',
        dataConsulta: '15/12/2023',
        horaConsulta: '14:00'
    },
    {
        id: 2,
        imagem: 'https://amafotos.s3.amazonaws.com/usuario6.png',
        nomeCompleto: 'Ednalva Maria da Silva Santana',
        nome: 'Ednalva Santana',
        cpf: '01112312302',
        dataNascimento: '1989-11-10',
        data: '24/10/2023',
        idade: '42',
        email: 'ednalva.sant@gmail.com',
        telefone: '81985529827',
        senha:'senha123',
        cep: '50050540',
        cidade: 'Recife',
        bairro: 'Santo Amaro',
        rua: 'Avenida Visconde de Suassuna',
        numero: '55',
        dataConsulta: '23/12/2023',
        horaConsulta: '14:00'
    },
    {
        id: 3,
        imagem: 'https://amafotos.s3.amazonaws.com/usuario8.png',
        nomeCompleto: 'Magda da Silva Pinheiro',
        nome: 'Magda Pinheiro',
        cpf: '01112312303',
        dataNascimento: '1989-11-10',
        data: '13/10/2023',
        idade: '32',
        email: 'pinheiro.magda@hotmail.com',
        telefone: '81985529827',
        senha:'senha123',
        cep: '50050540',
        cidade: 'Recife',
        bairro: 'Santo Amaro',
        rua: 'Avenida Visconde de Suassuna',
        numero: '55',
    },
    {
        id: 4,
        imagem: 'https://amafotos.s3.amazonaws.com/usuario5.jpg',
        nomeCompleto: 'Maria das Graças Tenório de Araujo',
        nome: 'Maria das Graças Araujo',
        cpf: '01112312304',
        dataNascimento: '1989-11-10',
        data: '27/09/2023',
        idade: '28',
        email: 'mdasgracas_tenorio@gmail.com',
        telefone: '81985529827',
        senha:'senha123',
        cep: '50050540',
        cidade: 'Recife',
        bairro: 'Santo Amaro',
        rua: 'Avenida Visconde de Suassuna',
        numero: '55',
        dataConsulta: '23/12/2023',
        horaConsulta: '08:00'
    },
    {
        id: 5,
        imagem: 'https://amafotos.s3.amazonaws.com/usuario1.jpg',
        nomeCompleto: 'Mônica Caetano',
        nome: 'Mônica Caetano',
        cpf: '01112312305',
        dataNascimento: '1989-11-10',
        data: '07/09/2023',
        idade: '28',
        email: 'monicac95@hotmail.com',
        telefone: '81985529827',
        senha:'senha123',
        cep: '50050540',
        cidade: 'Recife',
        bairro: 'Santo Amaro',
        rua: 'Avenida Visconde de Suassuna',
        numero: '55',
        dataConsulta: '16/12/2023',
        horaConsulta: '14:00'
    },
    {
        id: 6,
        imagem: 'https://amafotos.s3.amazonaws.com/usuario10.png',
        nomeCompleto: ' Cássia Valéria',
        nome: ' Cássia Valéria',
        cpf: '01112312306',
        dataNascimento: '1989-11-10',
        data: '22/08/2023',
        idade: '39',
        email: 'cassia_valeria22@gmail.com',
        telefone: '81985529827',
        senha:'senha123',
        cep: '50050540',
        cidade: 'Recife',
        bairro: 'Santo Amaro',
        rua: 'Avenida Visconde de Suassuna',
        numero: '55',
    },
    {
        id:7,
        imagem: 'https://amafotos.s3.amazonaws.com/usuario4.jpg',
        nomeCompleto: 'Izolda Antonia de Melo',
        nome: 'Antonia de Melo',
        cpf: '01112312307',
        dataNascimento: '1989-11-10',
        data: '02/11/2023',
        idade: '45',
        email: 'izolda_antonia@gmail.com',
        telefone: '81985529827',
        senha:'senha123',
        cep: '50050540',
        cidade: 'Recife',
        bairro: 'Santo Amaro',
        rua: 'Avenida Visconde de Suassuna',
        numero: '55',
        statusAtivo: false,
    },
    {
        id:8,
        imagem: 'https://amafotos.s3.amazonaws.com/usuario9.png',
        nomeCompleto: 'Waldineire Ferreira da Silva',
        nome: 'Neire Silva',
        cpf: '01112312308',
        dataNascimento: '1989-11-10',
        data: '02/11/2023',
        idade: '36',
        email: 'silvawaldireine@gmail.com',
        telefone: '81985529827',
        senha:'senha123',
        cep: '50050540',
        cidade: 'Recife',
        bairro: 'Santo Amaro',
        rua: 'Avenida Visconde de Suassuna',
        numero: '55',
        statusAtivo: false,
    },
    
]

export const agendamentos = [
    {
        idAgendamento: 1,
        data: '2023-12-15',
        hora: '14:00',
        idProfissional: 1,
        imagemProfissional: 'https://amaprofissionais.s3.amazonaws.com/pro4.png',
        nomeProfissional: 'Amélia Barros',
        profissao: 'Psicologia',
        idUsuario: 1,
        imagemUsuario: 'https://amafotos.s3.amazonaws.com/usuario7.png',
        nomeUsuario: 'Sandra Alencar',
    },
    {
        idAgendamento: 2,
        data: '2023-12-23',
        hora: '14:00',
        idProfissional: 1,
        imagemProfissional: 'https://amaprofissionais.s3.amazonaws.com/pro4.png',
        nomeProfissional: 'Amélia Barros',
        profissao: 'Psicologia',
        idUsuario: 2,
        imagemUsuario: 'https://amafotos.s3.amazonaws.com/usuario6.png',
        nomeUsuario: 'Ednalva Santana',
    },
    {
        idAgendamento: 3,
        data: '2024-01-06',
        hora: '08:00',
        idProfissional: 1,
        imagemProfissional: 'https://amaprofissionais.s3.amazonaws.com/pro4.png',
        nomeProfissional: 'Amélia Barros',
        profissao: 'Psicologia',
        idUsuario: 4,
        imagemUsuario: 'https://amafotos.s3.amazonaws.com/usuario5.jpg',
        nomeUsuario: 'Maria das Graças Araujo',
    },
    {
        idAgendamento: 4,
        data: '2023-12-22',
        hora: '08:00',
        idProfissional: 2,
        imagemProfissional: 'https://amaprofissionais.s3.amazonaws.com/lactarista.jpg',
        nomeProfissional: 'Fernanda Dias',
        profissao: 'Lactarista',
        idUsuario: 1,
        imagemUsuario: 'https://amafotos.s3.amazonaws.com/usuario7.png',
        nomeUsuario: 'Sandra Alencar',
    },
    {
        idAgendamento: 5,
        data: '2024-01-04',
        hora: '15:00',
        idProfissional: 5,
        imagemProfissional: 'https://amaprofissionais.s3.amazonaws.com/pro1.jpg',
        nomeProfissional: 'André Pereira',
        profissao: 'Enfermagem',
        idUsuario: 1,
        imagemUsuario: 'https://amafotos.s3.amazonaws.com/usuario7.png',
        nomeUsuario: 'Sandra Alencar',
    },
    {
        idAgendamento: 6,
        data: '2023-12-16',
        hora: '14:00',
        idProfissional: 1,
        imagemProfissional: 'https://amaprofissionais.s3.amazonaws.com/pro4.png',
        nomeProfissional: 'Amélia Barros',
        profissao: 'Psicologia',
        idUsuario: 5,
        imagemUsuario: 'https://amafotos.s3.amazonaws.com/usuario1.jpg',
        nomeUsuario: 'Mônica Caetano',
    },
]